name: Release

on:
  release:
      types: [ published ]

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install CDT
        run: |
          wget https://github.com/AntelopeIO/cdt/releases/download/v4.0.1/cdt_4.0.1_amd64.deb
          sudo apt install ./cdt_4.0.1_amd64.deb
      - run: cdt-cpp eosio.wram.cpp -I ./include
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            eosio.wram.wasm
            eosio.wram.abi